# -*- coding: utf-8 -*-
"""Diagrama_lineas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlvzXw1H_aUAKOrRGEjw7629BJgCVFBr
"""

#Este paso sobra dado que ya se debe haber implementado en otros archivos, sin embargo lo agrego
#Lo primero a hacer es importar la libreria matplotlib de la siguiente forma:😊
import matplotlib.pyplot as plt

# Definimos los datos en X y Y😊
x = [1, 2, 3, 4, 5]
y = [1, 4, 6, 8, 10]

# Crear gráfico de lineas se hace atraves de la función .plot (esta es la forma de especificar cual diagrama requiero)😊
plt.plot(x, y)

# Para mostrar el gráfico es con el .show (mas sin embargo no es necesario para plasmar nuestro grafico)😊
plt.show()

#Si requiero cambiar el color de la linea es añadiendo el atributo color y el color en inglés a usar a la función .plot😊
plt.plot(x, y, color='red')

#Si requiero que mi linea se vea de alguna otra forma, por ejemplo discontinua, se usar el atributo linestyle y el tipo
#Los tipos son: [
    # (--): discontinua no redondeada,
    # (-):solida,
    # (:):discontinua redondeada
    # (-.) : linea y punto, etc
    #] Si requieren más información de interlineados, lean la documentación 😊
plt.plot(x, y, linestyle='-.')

# Agrega círculos en los puntos de intersección mediante el atributo marker 😊
plt.plot(x, y, marker='o')

# Hace la línea más gruesa segun sea el valor que asigne en el atributo linewidth 😊
plt.plot(x, y, linewidth=5)

# Mediante la función title se le puede asignar a la función existente y creada previamente y se les puede asignar valores de color, tamaño como las funciones
plt.title("Grafico de ejemplo")
# Etiqueta del eje X
plt.xlabel("Eje X")
# Etiqueta del eje Y
plt.ylabel("Eje Y")