# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ld4nAcQomEmdYMxoH2hd7scPVxfwrw2P
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

archivo ="/content/drive/MyDrive/Datos.csv"
datos = pd.read_csv(archivo, sep=",", header=0, encoding="latin-1")
#Numero de filas y columnas
datos.shape
#Cambio las columnas
datos.columns = ['Code', 'LastName', 'FirstName', 'Gender', 'Age', 'InDate', 'Cargo', 'Ubication', 'Money', 'Bonification', 'Total']
#Cuento las filas de una columna
conteo = datos['Gender'].value_counts()
#Persona que mas gana
datos.loc[datos['Total'].idxmax(), ['FirstName', 'LastName', 'Total']]
#grafica
plt.xlabel("Género")
plt.ylabel("Cantidad")
conteo.plot(kind='bar', color=['purple', 'blue'])
plt.show()